/*
 * Autogenerated by fixcom.pl commands.h file with functions
 * for the MG Basic in the camera project
 * Input file: words
 */

byte codes[] = {"for\0to\0step\0next\0label\0goto\0gosub\0input\0\
print\0let\0rem\0if\0then\0else\0end\0stop\0\
poke\0data\0return\0restore\0dim\0while\0wend\0open\0\
close\0remove\0and\0or\0xor\0>=\0<=\0<\0\
>\0=\0<>\0-\0+\0/\0*\0,\0\
;\0(\0)\0get\0abs\0sgn\0rnd\0call\0\
peek\0read\0len\0asc\0dec\0instr\0mid$\0right$\0\
left$\0hex$\0second\0minute\0hour\0time\0ls\0mv\0\
rm\0cp\0save\0load\0cd\0pwd\0cat\0run\0\
list\0status\0dcvalue\0common\0\0"};
/*
 * Last codenumber is 204
 */
